[package]
name = "lettera"
version = "0.1.0"
authors = ["Andrea Cognolato <andrecogno@hotmail.it>"]
edition = "2018"

[dependencies]
gl = { path = "lib/gl" }
glutin = "0.22.0-alpha3"
freetype-rs = "0.21.0"
syntect = "3.2.1"
